[project]
name = 'stackflow-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = [
    { contract_id = "ST3F4WEX90KZQ6D25TWP09J90D6CSYGW1JX8WH3Y7.price-oracle-trait-v2" },
    { contract_id = "ST3F4WEX90KZQ6D25TWP09J90D6CSYGW1JX8WH3Y7.sip-010-trait-ft-standard" },
    { contract_id = "ST3F4WEX90KZQ6D25TWP09J90D6CSYGW1JX8WH3Y7.stackflow-options-m1" },
    { contract_id = "ST3F4WEX90KZQ6D25TWP09J90D6CSYGW1JX8WH3Y7.stackflow-options-v1" }
]
[contracts.price-oracle-trait-v2]
path = 'contracts/price-oracle-trait-v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-options-m1]
path = 'contracts/stackflow-options-m1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-options-v2]
path = 'contracts/stackflow-options-v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-options-m2-v2]
path = 'contracts/stackflow-options-m2-v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-options-v1]
path = 'contracts/stackflow-options-v1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-oracle-mock-v2]
path = 'contracts/stackflow-oracle-mock-v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-pyth-oracle-v2]
path = 'contracts/stackflow-pyth-oracle-v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackflow-sbtc-mock]
path = 'contracts/stackflow-sbtc-mock.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 1000000000000000

[accounts.wallet_1]
mnemonic = "legal winner thank year wave sausage worth useful legal winner thank yellow"
balance = 1000000000000000

[accounts.wallet_2]
mnemonic = "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
balance = 1000000000000000
