[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "REPLACE_WITH_YOUR_DEPLOYER_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_1]
mnemonic = "REPLACE_WITH_YOUR_WALLET_1_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_2]
mnemonic = "REPLACE_WITH_YOUR_WALLET_2_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_3]
mnemonic = "REPLACE_WITH_YOUR_WALLET_3_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_4]
mnemonic = "REPLACE_WITH_YOUR_WALLET_4_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_5]
mnemonic = "REPLACE_WITH_YOUR_WALLET_5_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_6]
mnemonic = "REPLACE_WITH_YOUR_WALLET_6_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_7]
mnemonic = "REPLACE_WITH_YOUR_WALLET_7_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_8]
mnemonic = "REPLACE_WITH_YOUR_WALLET_8_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.faucet]
mnemonic = "REPLACE_WITH_YOUR_FAUCET_MNEMONIC"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false
# disable_postgres = false
# disable_bitcoin_explorer = true
# working_dir = "tmp/devnet"
# stacks_node_events_observers = ["host.docker.internal:8002"]
# miner_mnemonic = "fragile loan twenty basic net assault jazz absorb diet talk art shock innocent float punch travel gadget embrace caught blossom hockey surround initial reduce"
# miner_derivation_path = "m/44'/5757'/0'/0/0"
# faucet_mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health outside kitten belt reform"
# faucet_derivation_path = "m/44'/5757'/0'/0/0"
# stacker_mnemonic = "empty lens any direct brother then drop fury rule pole win claim scissors list rescue horn rent inform relief jump sword weekend half legend"
# stacker_derivation_path = "m/44'/5757'/0'/0/0"
# orchestrator_port = 20445
# bitcoin_node_p2p_port = 18444
# bitcoin_node_rpc_port = 18443
# bitcoin_node_username = "devnet"
# bitcoin_node_password = "devnet"
# bitcoin_controller_block_time = 30_000
# stacks_node_rpc_port = 20443
# stacks_node_p2p_port = 20444
# stacks_api_port = 3999
# stacks_api_events_port = 3700
# bitcoin_explorer_port = 8001
# stacks_explorer_port = 8000
# postgres_port = 5432
# postgres_username = "postgres"
# postgres_password = "postgres"
# postgres_database = "postgres"
# bitcoin_node_image_url = "lncm/bitcoind:v27.2"
# stacks_node_image_url = "blockstack/stacks-blockchain:3.2.0.0.0-alpine"
# stacks_signer_image_url = "blockstack/stacks-signer:3.2.0.0.0.0-alpine"
# stacks_api_image_url = "hirosystems/stacks-blockchain-api:latest"
# stacks_explorer_image_url = "hirosystems/explorer:latest"
# bitcoin_explorer_image_url = "quay.io/hirosystems/bitcoin-explorer:devnet"
# postgres_image_url = "postgres:alpine"

# epoch_2_0 = 100
# epoch_2_05 = 100
# epoch_2_1 = 101
# epoch_2_2 = 102
# epoch_2_3 = 103
# epoch_2_4 = 104
# epoch_2_5 = 108
# epoch_3_0 = 142
# epoch_3_1 = 144
# epoch_3_2 = 146

# Send some stacking orders
[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_1"
slots = 2
btc_address = "mr1iPkD9N3RJZZxXRk7xF9d36gffa6exNC"

[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_2"
slots = 2
btc_address = "muYdXKmX9bByAueDe6KFfHd5Ff1gdN9ErG"

[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_3"
slots = 2
btc_address = "mvZtbibDAAA3WLpY7zXXFqRa3T4XSknBX7"

