[network]
name = "simnet"

[accounts.deployer]
mnemonic = 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about'
balance = 1000000000000000

[accounts.wallet_1]
mnemonic = 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about'
balance = 1000000000000000

[accounts.wallet_2]
mnemonic = 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about'
balance = 1000000000000000
